### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by z0r1k** [aiven/devportal#543] opened 2022-02-07 09:28 UTC
Hello there.

When I have a query like https://developer.aiven.io/search.html?q=prometheus+kafka+metrics I only get `Getting Started with New Relic` from the “help center”, but if I search via https://help.aiven.io/en/?q=prometheus+kafka+metrics I get many more results including `Kafka metrics through Prometheus` integration.

<img width="1205" alt="Screenshot 2022-02-07 at 10 26 12" src="https://user-images.githubusercontent.com/215975/152761235-ba7b6b46-e187-4743-af32-80c09fa4a71f.png">

<img width="936" alt="Screenshot 2022-02-07 at 10 26 56" src="https://user-images.githubusercontent.com/215975/152761246-c15bd5e2-8c9b-41ea-85e7-fe420240a94b.png">

Is dev portal search index somewhat outdated or something went wrong? 

Could be related to #122 

Ty.

**Comment by lornajane** [comment] 2022-04-16 19:00
I can't reproduce this now, and we shipped a bunch of improvements this week so I'm closing for now, let's re-open if we spot another situation where things don't seem quite right. Thanks @z0r1k for the original bug report!

**Closed by lornajane** 2022-04-16 19:00 UTC
Labels: platform
